### ISSUE TITLE
[Question/Suggestion] Updating from 4.2.x to 4.3.x on an existing world

### ISSUE THREAD

**Issue by Peter-Pwn** [Rohzek/SimpleOreGeneration#28]
Since you removed the ~~"vanilla"~~ _surface certus quartz_ ore blocks from your mod, updating a existing world would delete these ore blocks. Is there a way to tell forge/minecraft to exchange them instead?

**Comment by Rohzek** [comment]
Which "vanilla" ore blocks, do you mean?

**Comment by Peter-Pwn** [comment]
Ok, to say "vanilla" was a mistake. I thought in the old version all the vanilla ores (like iron) were overridden by your own ores. But it was only the surface certus quartz ores which caused the problem for me.

**Comment by Rohzek** [comment]
Nope. I've spawned vanilla ores as they were from the start. 
In 4.2.2 I removed my own versions of certus quartz and charged certus quartz, and spawned the AE2 versions instead, so going from 4.2.1 to 4.2.2+ that's an issue. But from 4.2.2 updating won't remove any ores.

But in 4.3.0 I removed Bronze Ingot, Block and Nugget since they weren't ore related, and were only added to try to fix an issue that had been fixed for a long time, (and most mods that you need bronze, have a way to mix them like an alloy smelter, that didn't craft mine, anyway.) A tiny issue, but not ore related.

As for re-spawning the certus quartz, I haven't looked into retrogen yet, so there's no real way to populate existing chunks, yet.

**Comment by Peter-Pwn** [comment]
I came too late for version 4.2.2 and updated directly to 4.3.1.

The best way might then to use MCEdit and replace the ores before updating the mod.
