### ISSUE TITLE
Crash to Desktop due to Null Pointer Exception

### ISSUE THREAD

**Issue by Zarepheth** [Rohzek/SimpleOreGeneration#3]
While walking about the Overworld, in a Biomes O'Plenty "Highlands" biome, the game crashes to the desktop. Reviewing the logs, it appears that a Null Point Exception occurs, then Forge/Minecraft spits out a crash report about an NPE in the server tick loop. I'm guessing some chuck generation was occuring and something went haywire...

[Log File on paste.ee](https://paste.ee/p/q2ylN)

Simple Ore Gen 3.2.0

**Comment by Rohzek** [comment]
Did you by any chance run/update from a previous version?

**Comment by Zarepheth** [comment]
Yes, I had previous versions. I started with 3.0.1, then 3.1.0, and now 3.2.0. The world which is crashing was started with 3.1.0.

**Comment by Rohzek** [comment]
Thanks for your continued support. :)

Try deleting/renaming the OreGen.json file inside of ~/config/simpleoregen, and trying again.

**Comment by Zarepheth** [comment]
Well, I renamed the OreGen.json file, then reloaded MineCraft. The game still crashed, but I'm pretty sure it was for a different reason - something weird is happening with the video... Anyway, I compared the old and new OreGen.json file - it appears you've added an option to disable each ore.

**Comment by Rohzek** [comment]
Mhm, and that's what I believe the NullPointerException was referring to.

If you'd like, I can take a look at the new crash log and see if I can help diagnose the problem at all.

**Comment by Zarepheth** [comment]
An NPE for a missing setting - that would make too much sense! And to confirm your beliefs, after rebooting my machine due to the video issues and returning to the game, the newest version of Simple Ore Gen, with the refreshed OreGen.json file, no longer crashes.

As for the video issues, I've not yet found the crash log for them. I think it's something between Java and the video drivers, perhaps with some contributions by a few video tampering mods (Dynamic Surroundings, Better FPS, or Optifine).

**Comment by Rohzek** [comment]
Well, I'm glad you have it mostly sorted out. Hope you figure out the video issues too.

---------------------------------------------------------------------------------------------------

Problem: NullPointerException on ore generation.

Solution: Regenerate OreGen.json by deletion/renaming the old file.

Additional info: OreGen.json was added in 3.1.0, and then further updated in 3.2.0 to include a new attribute ("disableOre") so that each ore can be individually disabled that is - completely removed from the game/not generated at all** 
Line 112 of SGWorldGen (where the supplied crash log reports the error) attempts to read that new attribute. [Here is the code](https://github.com/Rohzek/SimpleOreGeneration/blob/master/main/java/com/gmail/rohzek/world/SGWorldGen.java#L110-L227).
When updating from 3.1.0 to 3.2.0, the OreGen.json file needs to be re-generated to include this new attribute or it causes a NullPointerException when reading it is attempted (and it's subsequently not found).

**Comment by Zarepheth** [comment]
P.S. The vide problems were probably due to a failing video card. A few weeks after this it gave out such that only Window's default drivers would work - no gaming until a I replaced it with a new video card. :(
