### ISSUE TITLE
Cascading Worldgen Lag Error in Server

### ISSUE THREAD

**Issue by BSKCorp** [Rohzek/SimpleOreGeneration#30]
Is there any way to fix this, this is a new world. but Simple Ore Generation Loaded a new chunk [ X, X] in Dimension 0(overworld) while populating chunk [x,x] casing casading worldgen lag. 
Please report this to the mod's issue tracker. This log can be disabled in the forge config.
Using Forge 1.12.2-14.23.4.2760
Simple OreGen 4.3.2

**Comment by Rohzek** [comment]
Like: #10 #18 and #24 

This happens when ore spawns too close to the chunk border, and makes the next chunk spawn too. It's not a bug, just a side effect of ore generation, and the only way to "fix" it is to lower the number of ores that are trying to spawn. The only other thing I can really do about it is trying to change ore generation into a structure (like villages) instead of using the ore generation code, as I'm already using the offset vanilla uses.

And it not only should it not slow down anything too much, especially if my mod is the only one present handling major generation, but [vanilla Minecraft also occasionally has the same problem](https://github.com/MinecraftForge/MinecraftForge/blob/4fbc84773650580008295a234302fc5618af5fcb/patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch#L323), forge just decided to block it, so it **doesn't tell you** that it does.

**Comment by BSKCorp** [comment]
Ahh gotcha, well thank you very much for the direct info. Will head to the config and turn logging off for that then lol
